version: "3.4"

services:
    database:
        container_name: typo3-db
        build:
            context: .
            dockerfile: Dockerfile-database
        environment:
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_DATABASE=typo3
            - MYSQL_USER=typo3
            - MYSQL_PASSWORD=password
        ports:
            - "3306:3306"
        volumes:
            - ./docker_conf:/docker_conf
        networks:
            - phpmyadmin

    web:
        container_name: typo3-web
        build:
            context: .
            dockerfile: Dockerfile-web
        ports:
            - "8080:80"
        environment:
            - USERID=1000
            - GROUPID=1000
        volumes:
            - .:/var/www/html
        command: "sh docker_conf/folder_rights_correction.sh"
        depends_on:
            - database
        networks:
            - phpmyadmin
    
    phpmyadmin:
        container_name: typo3-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - database
        ports:
            - 8181:80
        environment:
            - PMA_HOST=database
            - PMA_ARBITRARY=1
        networks:
            - phpmyadmin

networks:
    phpmyadmin:
        driver: bridge